spring.application.name=CapIt-BackEnd


spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.igwaonsddbaudubcbzsa
spring.datasource.password=7f5e4c38-e90e-4e68-bc0c-0918c814981c
spring.datasource.driver-class-name=org.postgresql.Driver


spring.sql.init.mode=never





